from ontoumlpy.classes.ouenumeration.enumerations_class import (
    ONTOUML_BASE_SORTAL_CLASS_STEREOTYPES,
    ONTOUML_ULTIMATE_SORTAL_CLASS_STEREOTYPES,
    ONTOUML_SORTAL_CLASS_STEREOTYPES,
    ONTOUML_NON_SORTAL_CLASS_STEREOTYPES,
    ONTOUML_ABSTRACT_CLASS_STEREOTYPES,
    ONTOUML_RIGID_CLASS_STEREOTYPES,
    ONTOUML_ANTI_RIGID_CLASS_STEREOTYPES,
    ONTOUML_SEMI_RIGID_CLASS_STEREOTYPES,
    ONTOUML_CLASS_STEREOTYPES,
)
from ontoumlpy.classes.ouenumeration.enumerations_misc import (
    ONTOUML_RELATION_STEREOTYPES,
    ONTOUML_PROPERTY_STEREOTYPES,
    ONTOUML_AGGREGATION_KINDS,
    ONTOUML_ONTOLOGICAL_NATURES,
    ONTOUML_ABSTRACT_ELEMENTS,
    ONTOUML_CONCRETE_ELEMENTS,
)

DICT_TUPLES_SIZE = {
    ONTOUML_BASE_SORTAL_CLASS_STEREOTYPES: 4,
    ONTOUML_ULTIMATE_SORTAL_CLASS_STEREOTYPES: 7,
    ONTOUML_SORTAL_CLASS_STEREOTYPES: 11,
    ONTOUML_NON_SORTAL_CLASS_STEREOTYPES: 5,
    ONTOUML_ABSTRACT_CLASS_STEREOTYPES: 3,
    ONTOUML_RIGID_CLASS_STEREOTYPES: 8,
    ONTOUML_ANTI_RIGID_CLASS_STEREOTYPES: 6,
    ONTOUML_SEMI_RIGID_CLASS_STEREOTYPES: 1,
    ONTOUML_CLASS_STEREOTYPES: 21,
    ONTOUML_RELATION_STEREOTYPES: 19,
    ONTOUML_PROPERTY_STEREOTYPES: 2,
    ONTOUML_AGGREGATION_KINDS: 3,
    ONTOUML_ONTOLOGICAL_NATURES: 11,
    ONTOUML_ABSTRACT_ELEMENTS: 11,
    ONTOUML_CONCRETE_ELEMENTS: 10,
}
